(SimpleFunction.test)
@0                       // L-0
D=A                      // L-1
@SP                      // L-2
A=M                      // L-3
M=D                      // L-4
@SP                      // L-5
M=M+1                    // L-6
@0                       // L-7
D=A                      // L-8
@SP                      // L-9
A=M                      // L-10
M=D                      // L-11
@SP                      // L-12
M=M+1                    // L-13
@0                    // L-14
D=A                    // L-15
@LCL                   // L-16
A=M+D                  // L-17
D=M                    // L-18
@SP                    // L-19
A=M                    // L-20
M=D                    // L-21
@SP                    // L-22
M=M+1                  // L-23
@1                    // L-24
D=A                    // L-25
@LCL                   // L-26
A=M+D                  // L-27
D=M                    // L-28
@SP                    // L-29
A=M                    // L-30
M=D                    // L-31
@SP                    // L-32
M=M+1                  // L-33
@SP                    // L-34
M=M-1                  // L-35
A=M                    // L-36
D=M                    // L-37
@SP                    // L-38
M=M-1                  // L-39
A=M                    // L-40
M=M+D                  // L-41
@SP                    // L-42
M=M+1                  // L-43
@SP                    // L-44
M=M-1                  // L-45
A=M                    // L-46
M=!M                   // L-47
@SP                    // L-48
M=M+1                  // L-49
@0                    // L-50
D=A                    // L-51
@ARG                   // L-52
A=M+D                  // L-53
D=M                    // L-54
@SP                    // L-55
A=M                    // L-56
M=D                    // L-57
@SP                    // L-58
M=M+1                  // L-59
@SP                    // L-60
M=M-1                  // L-61
A=M                    // L-62
D=M                    // L-63
@SP                    // L-64
M=M-1                  // L-65
A=M                    // L-66
M=M+D                  // L-67
@SP                    // L-68
M=M+1                  // L-69
@1                    // L-70
D=A                    // L-71
@ARG                   // L-72
A=M+D                  // L-73
D=M                    // L-74
@SP                    // L-75
A=M                    // L-76
M=D                    // L-77
@SP                    // L-78
M=M+1                  // L-79
@SP                    // L-80
M=M-1                  // L-81
A=M                    // L-82
D=M                    // L-83
@SP                    // L-84
M=M-1                  // L-85
A=M                    // L-86
M=M-D                  // L-87
@SP                    // L-88
M=M+1                  // L-89
@0                         // L-90
D=A                        // L-91
@ARG                       // L-92
D=M+D                      // L-93
@R13                       // L-94
M=D                        // L-95
@SP                        // L-96
M=M-1                      // L-97
A=M                        // L-98
D=M                        // L-99
@R13                       // L-100
A=M                        // L-101
M=D                        // L-102
@ARG                       // L-103
D=M                        // L-104
@SP                        // L-105
M=D+1                      // L-106
@LCL                       // L-107
D=M                        // L-108
@R12                       // L-109
M=D                        // L-110
@R12                       // L-111
A=M-1                      // L-112
D=M                        // L-113
@THAT                      // L-114
M=D                        // L-115
@2                         // L-116
D=A                        // L-117
@R12                       // L-118
A=M-D                      // L-119
D=M                        // L-120
@THIS                      // L-121
M=D                        // L-122
@3                         // L-123
D=A                        // L-124
@R12                       // L-125
A=M-D                      // L-126
D=M                        // L-127
@ARG                       // L-128
M=D                        // L-129
@4                         // L-130
D=A                        // L-131
@R12                       // L-132
A=M-D                      // L-133
D=M                        // L-134
@LCL                       // L-135
M=D                        // L-136
@5                         // L-137
D=A                        // L-138
@R12                       // L-139
A=M-D                      // L-140
0;JMP                      // L-141
