@256                   // L-0
D=A                    // L-1
@SP                    // L-2
M=D                    // L-3

// call Sys.init 0
@return_0                 // L-4
D=A                        // L-5
@SP                        // L-6
A=M                        // L-7
M=D                        // L-8
@SP                        // L-9
M=M+1                      // L-10
@LCL                       // L-11
D=M                        // L-12
@SP                        // L-13
A=M                        // L-14
M=D                        // L-15
@SP                        // L-16
M=M+1                      // L-17
@ARG                       // L-18
D=M                        // L-19
@SP                        // L-20
A=M                        // L-21
M=D                        // L-22
@SP                        // L-23
M=M+1                      // L-24
@THIS                      // L-25
D=M                        // L-26
@SP                        // L-27
A=M                        // L-28
M=D                        // L-29
@SP                        // L-30
M=M+1                      // L-31
@THAT                      // L-32
D=M                        // L-33
@SP                        // L-34
A=M                        // L-35
M=D                        // L-36
@SP                        // L-37
M=M+1                      // L-38
@SP                        // L-39
D=M                        // L-40
@5                        // L-41
D=D-A                      // L-42
@ARG                       // L-43
M=D                        // L-44
@SP                        // L-45
D=M                        // L-46
@LCL                       // L-47
M=D                        // L-48
@Sys.init                        // L-49
0;JMP                      // L-50
(return_0)

// end call statement

// function Class1.set 0
(Class1.set)

// end function declaration
@0                    // L-51
D=A                    // L-52
@ARG                   // L-53
A=M+D                  // L-54
D=M                    // L-55
@SP                    // L-56
A=M                    // L-57
M=D                    // L-58
@SP                    // L-59
M=M+1                  // L-60
@SP                      // L-61
M=M-1                    // L-62
A=M                      // L-63
D=M                      // L-64
@16                      // L-65
M=D                      // L-66
@1                    // L-67
D=A                    // L-68
@ARG                   // L-69
A=M+D                  // L-70
D=M                    // L-71
@SP                    // L-72
A=M                    // L-73
M=D                    // L-74
@SP                    // L-75
M=M+1                  // L-76
@SP                      // L-77
M=M-1                    // L-78
A=M                      // L-79
D=M                      // L-80
@17                      // L-81
M=D                      // L-82
@0                    // L-83
D=A                    // L-84
@SP                    // L-85
A=M                    // L-86
M=D                    // L-87
@SP                    // L-88
M=M+1                  // L-89

// beginning return
@LCL                       // L-90
D=M                        // L-91
@R12                       // L-92
M=D                        // L-93
@5                         // L-94
A=D-A                      // L-95
D=M                        // L-96
@R15                       // L-97
M=D                        // L-98
@0                         // L-99
D=A                        // L-100
@ARG                       // L-101
D=M+D                      // L-102
@R13                       // L-103
M=D                        // L-104
@SP                        // L-105
M=M-1                      // L-106
A=M                        // L-107
D=M                        // L-108
@R13                       // L-109
A=M                        // L-110
M=D                        // L-111
@ARG                       // L-112
D=M                        // L-113
@SP                        // L-114
M=D+1                      // L-115
@R12                       // L-116
A=M-1                      // L-117
D=M                        // L-118
@THAT                      // L-119
M=D                        // L-120
@2                         // L-121
D=A                        // L-122
@R12                       // L-123
A=M-D                      // L-124
D=M                        // L-125
@THIS                      // L-126
M=D                        // L-127
@3                         // L-128
D=A                        // L-129
@R12                       // L-130
A=M-D                      // L-131
D=M                        // L-132
@ARG                       // L-133
M=D                        // L-134
@4                         // L-135
D=A                        // L-136
@R12                       // L-137
A=M-D                      // L-138
D=M                        // L-139
@LCL                       // L-140
M=D                        // L-141
@R15                       // L-142
A=M                        // L-143
0;JMP                      // L-144

// end return

// function Class1.get 0
(Class1.get)

// end function declaration
@16                      // L-145
D=M                      // L-146
@SP                      // L-147
A=M                      // L-148
M=D                      // L-149
@SP                      // L-150
M=M+1                    // L-151
@17                      // L-152
D=M                      // L-153
@SP                      // L-154
A=M                      // L-155
M=D                      // L-156
@SP                      // L-157
M=M+1                    // L-158
@SP                    // L-159
M=M-1                  // L-160
A=M                    // L-161
D=M                    // L-162
@SP                    // L-163
M=M-1                  // L-164
A=M                    // L-165
M=M-D                  // L-166
@SP                    // L-167
M=M+1                  // L-168

// beginning return
@LCL                       // L-169
D=M                        // L-170
@R12                       // L-171
M=D                        // L-172
@5                         // L-173
A=D-A                      // L-174
D=M                        // L-175
@R15                       // L-176
M=D                        // L-177
@0                         // L-178
D=A                        // L-179
@ARG                       // L-180
D=M+D                      // L-181
@R13                       // L-182
M=D                        // L-183
@SP                        // L-184
M=M-1                      // L-185
A=M                        // L-186
D=M                        // L-187
@R13                       // L-188
A=M                        // L-189
M=D                        // L-190
@ARG                       // L-191
D=M                        // L-192
@SP                        // L-193
M=D+1                      // L-194
@R12                       // L-195
A=M-1                      // L-196
D=M                        // L-197
@THAT                      // L-198
M=D                        // L-199
@2                         // L-200
D=A                        // L-201
@R12                       // L-202
A=M-D                      // L-203
D=M                        // L-204
@THIS                      // L-205
M=D                        // L-206
@3                         // L-207
D=A                        // L-208
@R12                       // L-209
A=M-D                      // L-210
D=M                        // L-211
@ARG                       // L-212
M=D                        // L-213
@4                         // L-214
D=A                        // L-215
@R12                       // L-216
A=M-D                      // L-217
D=M                        // L-218
@LCL                       // L-219
M=D                        // L-220
@R15                       // L-221
A=M                        // L-222
0;JMP                      // L-223

// end return

// function Class2.set 0
(Class2.set)

// end function declaration
@0                    // L-224
D=A                    // L-225
@ARG                   // L-226
A=M+D                  // L-227
D=M                    // L-228
@SP                    // L-229
A=M                    // L-230
M=D                    // L-231
@SP                    // L-232
M=M+1                  // L-233
@SP                      // L-234
M=M-1                    // L-235
A=M                      // L-236
D=M                      // L-237
@18                      // L-238
M=D                      // L-239
@1                    // L-240
D=A                    // L-241
@ARG                   // L-242
A=M+D                  // L-243
D=M                    // L-244
@SP                    // L-245
A=M                    // L-246
M=D                    // L-247
@SP                    // L-248
M=M+1                  // L-249
@SP                      // L-250
M=M-1                    // L-251
A=M                      // L-252
D=M                      // L-253
@19                      // L-254
M=D                      // L-255
@0                    // L-256
D=A                    // L-257
@SP                    // L-258
A=M                    // L-259
M=D                    // L-260
@SP                    // L-261
M=M+1                  // L-262

// beginning return
@LCL                       // L-263
D=M                        // L-264
@R12                       // L-265
M=D                        // L-266
@5                         // L-267
A=D-A                      // L-268
D=M                        // L-269
@R15                       // L-270
M=D                        // L-271
@0                         // L-272
D=A                        // L-273
@ARG                       // L-274
D=M+D                      // L-275
@R13                       // L-276
M=D                        // L-277
@SP                        // L-278
M=M-1                      // L-279
A=M                        // L-280
D=M                        // L-281
@R13                       // L-282
A=M                        // L-283
M=D                        // L-284
@ARG                       // L-285
D=M                        // L-286
@SP                        // L-287
M=D+1                      // L-288
@R12                       // L-289
A=M-1                      // L-290
D=M                        // L-291
@THAT                      // L-292
M=D                        // L-293
@2                         // L-294
D=A                        // L-295
@R12                       // L-296
A=M-D                      // L-297
D=M                        // L-298
@THIS                      // L-299
M=D                        // L-300
@3                         // L-301
D=A                        // L-302
@R12                       // L-303
A=M-D                      // L-304
D=M                        // L-305
@ARG                       // L-306
M=D                        // L-307
@4                         // L-308
D=A                        // L-309
@R12                       // L-310
A=M-D                      // L-311
D=M                        // L-312
@LCL                       // L-313
M=D                        // L-314
@R15                       // L-315
A=M                        // L-316
0;JMP                      // L-317

// end return

// function Class2.get 0
(Class2.get)

// end function declaration
@18                      // L-318
D=M                      // L-319
@SP                      // L-320
A=M                      // L-321
M=D                      // L-322
@SP                      // L-323
M=M+1                    // L-324
@19                      // L-325
D=M                      // L-326
@SP                      // L-327
A=M                      // L-328
M=D                      // L-329
@SP                      // L-330
M=M+1                    // L-331
@SP                    // L-332
M=M-1                  // L-333
A=M                    // L-334
D=M                    // L-335
@SP                    // L-336
M=M-1                  // L-337
A=M                    // L-338
M=M-D                  // L-339
@SP                    // L-340
M=M+1                  // L-341

// beginning return
@LCL                       // L-342
D=M                        // L-343
@R12                       // L-344
M=D                        // L-345
@5                         // L-346
A=D-A                      // L-347
D=M                        // L-348
@R15                       // L-349
M=D                        // L-350
@0                         // L-351
D=A                        // L-352
@ARG                       // L-353
D=M+D                      // L-354
@R13                       // L-355
M=D                        // L-356
@SP                        // L-357
M=M-1                      // L-358
A=M                        // L-359
D=M                        // L-360
@R13                       // L-361
A=M                        // L-362
M=D                        // L-363
@ARG                       // L-364
D=M                        // L-365
@SP                        // L-366
M=D+1                      // L-367
@R12                       // L-368
A=M-1                      // L-369
D=M                        // L-370
@THAT                      // L-371
M=D                        // L-372
@2                         // L-373
D=A                        // L-374
@R12                       // L-375
A=M-D                      // L-376
D=M                        // L-377
@THIS                      // L-378
M=D                        // L-379
@3                         // L-380
D=A                        // L-381
@R12                       // L-382
A=M-D                      // L-383
D=M                        // L-384
@ARG                       // L-385
M=D                        // L-386
@4                         // L-387
D=A                        // L-388
@R12                       // L-389
A=M-D                      // L-390
D=M                        // L-391
@LCL                       // L-392
M=D                        // L-393
@R15                       // L-394
A=M                        // L-395
0;JMP                      // L-396

// end return

// function Sys.init 0
(Sys.init)

// end function declaration
@6                    // L-397
D=A                    // L-398
@SP                    // L-399
A=M                    // L-400
M=D                    // L-401
@SP                    // L-402
M=M+1                  // L-403
@8                    // L-404
D=A                    // L-405
@SP                    // L-406
A=M                    // L-407
M=D                    // L-408
@SP                    // L-409
M=M+1                  // L-410

// call Class1.set 2
@return_1                 // L-411
D=A                        // L-412
@SP                        // L-413
A=M                        // L-414
M=D                        // L-415
@SP                        // L-416
M=M+1                      // L-417
@LCL                       // L-418
D=M                        // L-419
@SP                        // L-420
A=M                        // L-421
M=D                        // L-422
@SP                        // L-423
M=M+1                      // L-424
@ARG                       // L-425
D=M                        // L-426
@SP                        // L-427
A=M                        // L-428
M=D                        // L-429
@SP                        // L-430
M=M+1                      // L-431
@THIS                      // L-432
D=M                        // L-433
@SP                        // L-434
A=M                        // L-435
M=D                        // L-436
@SP                        // L-437
M=M+1                      // L-438
@THAT                      // L-439
D=M                        // L-440
@SP                        // L-441
A=M                        // L-442
M=D                        // L-443
@SP                        // L-444
M=M+1                      // L-445
@SP                        // L-446
D=M                        // L-447
@7                        // L-448
D=D-A                      // L-449
@ARG                       // L-450
M=D                        // L-451
@SP                        // L-452
D=M                        // L-453
@LCL                       // L-454
M=D                        // L-455
@Class1.set                        // L-456
0;JMP                      // L-457
(return_1)

// end call statement
@SP                      // L-458
M=M-1                    // L-459
A=M                      // L-460
D=M                      // L-461
@R5                     // L-462
M=D                      // L-463
@23                    // L-464
D=A                    // L-465
@SP                    // L-466
A=M                    // L-467
M=D                    // L-468
@SP                    // L-469
M=M+1                  // L-470
@15                    // L-471
D=A                    // L-472
@SP                    // L-473
A=M                    // L-474
M=D                    // L-475
@SP                    // L-476
M=M+1                  // L-477

// call Class2.set 2
@return_2                 // L-478
D=A                        // L-479
@SP                        // L-480
A=M                        // L-481
M=D                        // L-482
@SP                        // L-483
M=M+1                      // L-484
@LCL                       // L-485
D=M                        // L-486
@SP                        // L-487
A=M                        // L-488
M=D                        // L-489
@SP                        // L-490
M=M+1                      // L-491
@ARG                       // L-492
D=M                        // L-493
@SP                        // L-494
A=M                        // L-495
M=D                        // L-496
@SP                        // L-497
M=M+1                      // L-498
@THIS                      // L-499
D=M                        // L-500
@SP                        // L-501
A=M                        // L-502
M=D                        // L-503
@SP                        // L-504
M=M+1                      // L-505
@THAT                      // L-506
D=M                        // L-507
@SP                        // L-508
A=M                        // L-509
M=D                        // L-510
@SP                        // L-511
M=M+1                      // L-512
@SP                        // L-513
D=M                        // L-514
@7                        // L-515
D=D-A                      // L-516
@ARG                       // L-517
M=D                        // L-518
@SP                        // L-519
D=M                        // L-520
@LCL                       // L-521
M=D                        // L-522
@Class2.set                        // L-523
0;JMP                      // L-524
(return_2)

// end call statement
@SP                      // L-525
M=M-1                    // L-526
A=M                      // L-527
D=M                      // L-528
@R5                     // L-529
M=D                      // L-530

// call Class1.get 0
@return_3                 // L-531
D=A                        // L-532
@SP                        // L-533
A=M                        // L-534
M=D                        // L-535
@SP                        // L-536
M=M+1                      // L-537
@LCL                       // L-538
D=M                        // L-539
@SP                        // L-540
A=M                        // L-541
M=D                        // L-542
@SP                        // L-543
M=M+1                      // L-544
@ARG                       // L-545
D=M                        // L-546
@SP                        // L-547
A=M                        // L-548
M=D                        // L-549
@SP                        // L-550
M=M+1                      // L-551
@THIS                      // L-552
D=M                        // L-553
@SP                        // L-554
A=M                        // L-555
M=D                        // L-556
@SP                        // L-557
M=M+1                      // L-558
@THAT                      // L-559
D=M                        // L-560
@SP                        // L-561
A=M                        // L-562
M=D                        // L-563
@SP                        // L-564
M=M+1                      // L-565
@SP                        // L-566
D=M                        // L-567
@5                        // L-568
D=D-A                      // L-569
@ARG                       // L-570
M=D                        // L-571
@SP                        // L-572
D=M                        // L-573
@LCL                       // L-574
M=D                        // L-575
@Class1.get                        // L-576
0;JMP                      // L-577
(return_3)

// end call statement

// call Class2.get 0
@return_4                 // L-578
D=A                        // L-579
@SP                        // L-580
A=M                        // L-581
M=D                        // L-582
@SP                        // L-583
M=M+1                      // L-584
@LCL                       // L-585
D=M                        // L-586
@SP                        // L-587
A=M                        // L-588
M=D                        // L-589
@SP                        // L-590
M=M+1                      // L-591
@ARG                       // L-592
D=M                        // L-593
@SP                        // L-594
A=M                        // L-595
M=D                        // L-596
@SP                        // L-597
M=M+1                      // L-598
@THIS                      // L-599
D=M                        // L-600
@SP                        // L-601
A=M                        // L-602
M=D                        // L-603
@SP                        // L-604
M=M+1                      // L-605
@THAT                      // L-606
D=M                        // L-607
@SP                        // L-608
A=M                        // L-609
M=D                        // L-610
@SP                        // L-611
M=M+1                      // L-612
@SP                        // L-613
D=M                        // L-614
@5                        // L-615
D=D-A                      // L-616
@ARG                       // L-617
M=D                        // L-618
@SP                        // L-619
D=M                        // L-620
@LCL                       // L-621
M=D                        // L-622
@Class2.get                        // L-623
0;JMP                      // L-624
(return_4)

// end call statement
(WHILE)
@WHILE                        // L-625
0;JMP                      // L-626
